- hosts: all

  collections:
    - amazon.aws

  tasks:
    - name: create a public zone
      amazon.aws.route53_zone:
        zone: "{{ cluster_deployment.baseDomain | default('example.com') }}"
        comment: Cluster deployment zone
