- hosts: ibm

  tasks:
    - name: Spawn machine
      ansible.builtin.command: "sh /root/webapp/host_scripts/create_vms_from_iso_path.sh '{{ url }}' 3 om"

- hosts: localhost

  collections:
    - kubernetes.core

  tasks:
    - name: Wait till the Object is created
      kubernetes.core.k8s_info:
        kubeconfig: /home/omachace/.kube/config
        kind: Agent
        api_version: "agent-install.openshift.io/v1beta1"
        namespace: agent-infra
      register: agents
      until: "agents.resources | default([]) | length >= 3"
      delay: 20
      retries: 25
      ignore_errors: True

    - name: Approve hosts
      kubernetes.core.k8s:
        kubeconfig: /home/omachace/.kube/config
        state: patched
        kind: Agent
        api_version: "agent-install.openshift.io/v1beta1"
        namespace: agent-infra
        name: "{{ item.metadata.name }}"
        definition:
          spec:
            approved: true
      with_items: "{{ agents.resources }}"
