- name: Remove info about vmware system
  hosts: all
  gather_facts: false

  tasks:
    - name: Delete config map with fetched VMware data
      kubernetes.core.k8s:
        state: absent
        name: vmware-viewer
        namespace: default
        api_version: v1
        kind: ConfigMap

    - name: Delete deployment with vmware data
      kubernetes.core.k8s:
        state: absent
        name: vmware-viewer
        namespace: default
        api_version: apps/v1
        kind: Deployment

    - name: Delete service for vmware data app
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Service
        name: vmware-viewer
        namespace: default

    - name: Delete route for vmware data app
      kubernetes.core.k8s:
        state: absent
        kind: Route
        api_version: route.openshift.io/v1
        name: vmware-viewer
        namespace: default
