---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  containers:
    - name: page-down
      image: alpine:latest
      command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  containers:
    - name: page-down
      image: alpine:latest
      command: ["sleep", "infinity"]
---
